### ISSUE TITLE
Why not YOLO for Object Detection?

### ISSUE THREAD

**Issue by nmditai** [dvlab-research/ECCV22-P3AFormer-Tracking-Objects-as-Pixel-wise-Distributions#1]

**Comment by sjtuytc** [comment]
It's a good question. We start our approach under the transformer setting because transformers are really hot nowadays. However, we believe our proposed tracking paradigm may also generalize to YOLO-like detectors (e.g. by only modifying some heads of YOLO detectors). We are now trying this idea and we will add this to the repo as long as we get some new results.
